# Generated by Django 5.2.5 on 2025-09-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('project', '0004_migrate_editor_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Competitor domain to track (e.g., example.com)', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Optional name for this competitor', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='project.project')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('project', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='TargetKeywordRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, help_text='0 means not ranking')),
                ('rank_url', models.URLField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ranks', to='keywords.keyword')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_ranks', to='competitors.target')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['target', 'keyword'], name='competitors_target__42b0b1_idx'), models.Index(fields=['keyword', 'rank'], name='competitors_keyword_894832_idx')],
                'unique_together': {('target', 'keyword')},
            },
        ),
    ]
