# Generated by Django 5.2.5 on 2025-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if manually added by user, False if auto-discovered'),
        ),
    ]
