# Generated by Django 5.2.5 on 2025-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_add_is_manual_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='is_manual',
            field=models.BooleanField(default=True, help_text='True if manually added by user'),
        ),
    ]
