# Generated by Django 5.2.5 on 2025-09-06 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0007_remove_unused_dataforseo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Domain being analyzed', max_length=255)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('lost_date', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('backlinks', models.IntegerField(default=0)),
                ('backlinks_spam_score', models.IntegerField(default=0)),
                ('crawled_pages', models.IntegerField(default=0)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('cms', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('target_spam_score', models.IntegerField(default=0)),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('broken_backlinks', models.IntegerField(default=0)),
                ('broken_pages', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
                ('referring_domains_nofollow', models.IntegerField(default=0)),
                ('referring_main_domains', models.IntegerField(default=0)),
                ('referring_main_domains_nofollow', models.IntegerField(default=0)),
                ('referring_ips', models.IntegerField(default=0)),
                ('referring_subnets', models.IntegerField(default=0)),
                ('referring_pages', models.IntegerField(default=0)),
                ('referring_pages_nofollow', models.IntegerField(default=0)),
                ('referring_links_tld', models.JSONField(default=dict)),
                ('referring_links_types', models.JSONField(default=dict)),
                ('referring_links_attributes', models.JSONField(default=dict)),
                ('referring_links_platform_types', models.JSONField(default=dict)),
                ('referring_links_semantic_locations', models.JSONField(default=dict)),
                ('referring_links_countries', models.JSONField(default=dict)),
                ('platform_type', models.JSONField(default=list)),
                ('full_summary_data', models.JSONField(default=dict, help_text='Complete DataForSEO API response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_profiles', to='project.project')),
            ],
            options={
                'db_table': 'backlinks_profile',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BacklinkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('backlinks', models.IntegerField(default=0)),
                ('backlinks_spam_score', models.IntegerField(default=0)),
                ('crawled_pages', models.IntegerField(default=0)),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('broken_backlinks', models.IntegerField(default=0)),
                ('broken_pages', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
                ('referring_domains_nofollow', models.IntegerField(default=0)),
                ('referring_main_domains', models.IntegerField(default=0)),
                ('referring_main_domains_nofollow', models.IntegerField(default=0)),
                ('referring_ips', models.IntegerField(default=0)),
                ('referring_subnets', models.IntegerField(default=0)),
                ('referring_pages', models.IntegerField(default=0)),
                ('referring_pages_nofollow', models.IntegerField(default=0)),
                ('referring_links_tld', models.JSONField(default=dict)),
                ('referring_links_types', models.JSONField(default=dict)),
                ('referring_links_attributes', models.JSONField(default=dict)),
                ('referring_links_platform_types', models.JSONField(default=dict)),
                ('referring_links_semantic_locations', models.JSONField(default=dict)),
                ('referring_links_countries', models.JSONField(default=dict)),
                ('full_summary_data', models.JSONField(default=dict, help_text='Complete DataForSEO API response snapshot')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backlink_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='backlinks.backlinkprofile')),
            ],
            options={
                'db_table': 'backlinks_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backlinkprofile',
            index=models.Index(fields=['project', 'target'], name='backlinks_p_project_3a452c_idx'),
        ),
        migrations.AddIndex(
            model_name='backlinkprofile',
            index=models.Index(fields=['project', 'rank'], name='backlinks_p_project_e21e28_idx'),
        ),
        migrations.AddIndex(
            model_name='backlinkprofile',
            index=models.Index(fields=['project', 'backlinks'], name='backlinks_p_project_8e841f_idx'),
        ),
        migrations.AddIndex(
            model_name='backlinkprofile',
            index=models.Index(fields=['updated_at'], name='backlinks_p_updated_7858d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backlinkprofile',
            unique_together={('project', 'target')},
        ),
        migrations.AddIndex(
            model_name='backlinkhistory',
            index=models.Index(fields=['backlink_profile', 'created_at'], name='backlinks_h_backlin_abd61a_idx'),
        ),
        migrations.AddIndex(
            model_name='backlinkhistory',
            index=models.Index(fields=['created_at'], name='backlinks_h_created_6a6835_idx'),
        ),
    ]
