# Generated by Django 5.2.5 on 2025-09-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlinkhistory',
            name='crawled_pages',
        ),
        migrations.RemoveField(
            model_name='backlinkhistory',
            name='full_summary_data',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='cms',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='crawled_pages',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='full_summary_data',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='lost_date',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='platform_type',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='server',
        ),
        migrations.RemoveField(
            model_name='backlinkprofile',
            name='target_spam_score',
        ),
    ]
