# Generated by Django 5.2.5 on 2025-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlinks', '0002_remove_backlinkhistory_crawled_pages_and_more'),
        ('project', '0007_remove_unused_dataforseo_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlinkhistory',
            name='backlink_profile',
        ),
        migrations.AlterModelOptions(
            name='backlinkprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='backlinkprofile',
            name='backlinks_p_updated_7858d8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='backlinkprofile',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='backlinkprofile',
            index=models.Index(fields=['created_at'], name='backlinks_p_created_0e314a_idx'),
        ),
        migrations.DeleteModel(
            name='BacklinkHistory',
        ),
    ]
