# Generated by Django 5.2.5 on 2025-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlinks', '0003_remove_backlinkhistory_backlink_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlinkprofile',
            name='backlinks_collected_at',
            field=models.DateTimeField(blank=True, help_text='When detailed backlinks were last collected', null=True),
        ),
        migrations.AddField(
            model_name='backlinkprofile',
            name='backlinks_count_collected',
            field=models.IntegerField(default=0, help_text='Number of detailed backlinks collected'),
        ),
        migrations.AddField(
            model_name='backlinkprofile',
            name='backlinks_file_path',
            field=models.CharField(blank=True, help_text='R2 path for detailed backlinks file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='backlinkprofile',
            name='previous_summary',
            field=models.JSONField(default=dict, help_text='Previous summary data before update'),
        ),
    ]
