# Generated by Django 5.2.5 on 2025-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screamingfroglicense',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time expiry reminder was sent', null=True),
        ),
    ]
