# Generated by Django 5.2.5 on 2025-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteaudit',
            name='blocked_by_robots_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='broken_links_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='duplicate_content_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='duplicate_meta_descriptions_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='duplicate_titles_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='missing_hreflang_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='missing_meta_descriptions_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='missing_titles_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='redirect_chains_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='spelling_errors_count',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='total_issues_count',
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='overview',
            field=models.JSONField(blank=True, default=list, help_text='Issues overview from issues_overview_report.csv sorted by priority'),
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current audit status', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteaudit',
            name='manual_audit_frequency_days',
            field=models.IntegerField(default=1, help_text='Days between manual audits (minimum 1)'),
        ),
        migrations.DeleteModel(
            name='SiteIssue',
        ),
    ]
