# Generated by Django 5.2.5 on 2025-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='overall_site_health_score',
            field=models.FloatField(blank=True, help_text='Combined score: 60% technical SEO + 40% performance', null=True),
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='performance_score_desktop',
            field=models.IntegerField(blank=True, help_text='Latest desktop performance score from Lighthouse', null=True),
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='performance_score_mobile',
            field=models.IntegerField(blank=True, help_text='Latest mobile performance score from Lighthouse', null=True),
        ),
    ]
