# Generated by Django 5.2.5 on 2025-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0002_remove_siteaudit_blocked_by_robots_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='temp_audit_dir',
            field=models.CharField(blank=True, help_text='Path to temporary directory containing latest crawl results', max_length=500, null=True),
        ),
    ]
