# Generated by Django 5.2.5 on 2025-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0002_siteaudit_overall_site_health_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaudit',
            name='overall_site_health_score',
            field=models.FloatField(blank=True, help_text='Technical SEO health score based on issue density (100% technical)', null=True),
        ),
    ]
