# Generated by Django 5.2.5 on 2025-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0003_siteaudit_temp_audit_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='crawl_overview',
            field=models.JSONField(blank=True, default=dict, help_text='Crawl overview data including URLs encountered, crawled, and top inlinks'),
        ),
    ]
