# Generated by Django 5.2.5 on 2025-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0003_alter_siteaudit_overall_site_health_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteissue',
            name='issue_type',
            field=models.CharField(choices=[('missing_title', 'Missing Page Title'), ('duplicate_title', 'Duplicate Page Title'), ('title_too_long', 'Page Title Too Long (>60 chars)'), ('title_too_short', 'Page Title Too Short (<30 chars)'), ('title_pixel_width', 'Title Pixel Width Too Long (>600px)'), ('missing_meta_description', 'Missing Meta Description'), ('duplicate_meta_description', 'Duplicate Meta Description'), ('meta_description_too_long', 'Meta Description Too Long (>160 chars)'), ('meta_description_too_short', 'Meta Description Too Short (<70 chars)'), ('meta_pixel_width', 'Meta Description Pixel Width Too Long'), ('missing_h1', 'Missing H1 Tag'), ('multiple_h1', 'Multiple H1 Tags'), ('duplicate_h1', 'Duplicate H1 Tag'), ('h1_too_long', 'H1 Too Long (>70 chars)'), ('h1_too_short', 'H1 Too Short (<20 chars)'), ('missing_h2', 'Missing H2 Tags'), ('duplicate_h2', 'Duplicate H2 Tags'), ('duplicate_content', 'Exact Duplicate Content'), ('near_duplicate', 'Near Duplicate Content'), ('thin_content', 'Low Word Count/Thin Content'), ('canonical_issue', 'Canonicalization Issue'), ('canonical_chain', 'Canonical Chain'), ('canonical_loop', 'Canonical Loop'), ('noindex_page', 'Noindex Page'), ('orphan_page', 'Orphan Page (No Internal Links)'), ('missing_alt_text', 'Missing Alt Text on Images'), ('missing_alt_linked', 'Missing Alt Text on Linked Images'), ('image_too_large', 'Image Too Large (>100KB)'), ('broken_image', 'Missing/Broken Image'), ('broken_internal_link', 'Broken Internal Link (404/5xx)'), ('broken_external_link', 'Broken External Link'), ('redirect_chain', 'Redirect Chain'), ('redirect_loop', 'Redirect Loop'), ('temporary_redirect', 'Temporary Redirect (302)'), ('permanent_redirect', 'Permanent Redirect (301)'), ('blocked_by_robots', 'Link Blocked by Robots.txt'), ('internal_nofollow', 'Internal Nofollow Link'), ('external_nofollow', 'External Nofollow Link'), ('missing_canonical', 'Missing Canonical Tag'), ('conflicting_canonical', 'Conflicting Canonical Tags'), ('multiple_canonical', 'Multiple Canonical Tags'), ('hreflang_missing_return', 'Hreflang Missing Return Link'), ('hreflang_invalid_code', 'Hreflang Invalid Language Code'), ('hreflang_no_self', 'Hreflang No Self-Reference'), ('meta_robots_issue', 'Meta Robots Tag Issue'), ('x_robots_issue', 'X-Robots-Tag Issue'), ('amp_error', 'AMP Error'), ('sitemap_mismatch', 'URL in Sitemap Not on Site'), ('sitemap_noindex', 'Sitemap Contains Noindex URLs'), ('sitemap_missing', 'Page Missing from Sitemap'), ('robots_blocked_resource', 'Robots.txt Blocked Resource'), ('crawl_depth_issue', 'Excessive Crawl Depth'), ('slow_page', 'Slow Page Load (>3s)'), ('mobile_usability', 'Mobile Usability Issue'), ('mixed_content', 'Mixed Content (HTTP on HTTPS)'), ('http_https_mismatch', 'HTTP/HTTPS Inconsistency'), ('non_200_status', 'Non-200 Status Code'), ('missing_structured_data', 'Missing Structured Data')], max_length=50),
        ),
    ]
