# Generated by Django 5.2.5 on 2025-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0004_siteaudit_crawl_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteaudit',
            name='overview',
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='issues_overview',
            field=models.JSONField(blank=True, default=dict, help_text='Issues overview from issues_overview_report.csv sorted by priority'),
        ),
    ]
