# Generated by Django 5.2.5 on 2025-08-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0005_rename_overview_to_issues_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('issue_type', models.CharField(db_index=True, max_length=100)),
                ('issue_category', models.CharField(choices=[('meta_content', 'Meta Content'), ('response_code', 'Response Code'), ('image', 'Image'), ('technical_seo', 'Technical SEO'), ('content_quality', 'Content Quality'), ('security', 'Security')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20)),
                ('issue_data', models.JSONField(default=dict)),
                ('indexability', models.CharField(blank=True, max_length=50)),
                ('indexability_status', models.CharField(blank=True, max_length=100)),
                ('inlinks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='site_audit.siteaudit')),
            ],
            options={
                'ordering': ['severity', 'issue_type', 'url'],
                'indexes': [models.Index(fields=['site_audit', 'severity'], name='site_audit__site_au_48b574_idx'), models.Index(fields=['site_audit', 'issue_category'], name='site_audit__site_au_2c0192_idx'), models.Index(fields=['site_audit', 'issue_type'], name='site_audit__site_au_a831db_idx')],
            },
        ),
    ]
