# Generated by Django 5.2.5 on 2025-08-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0006_siteissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='desktop_performance',
            field=models.JSONField(blank=True, default=dict, help_text='Desktop PageSpeed Insights data including scores, core web vitals, and lab metrics'),
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='mobile_performance',
            field=models.JSONField(blank=True, default=dict, help_text='Mobile PageSpeed Insights data including scores, core web vitals, and lab metrics'),
        ),
        migrations.AlterField(
            model_name='siteaudit',
            name='performance_score_desktop',
            field=models.IntegerField(blank=True, help_text='Latest desktop performance score from PageSpeed Insights', null=True),
        ),
        migrations.AlterField(
            model_name='siteaudit',
            name='performance_score_mobile',
            field=models.IntegerField(blank=True, help_text='Latest mobile performance score from PageSpeed Insights', null=True),
        ),
    ]
