# Generated by Django 5.2.5 on 2025-08-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0007_add_pagespeed_insights_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteissue',
            name='first_detected_audit',
            field=models.ForeignKey(blank=True, help_text='The audit where this issue was first detected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_detected_issues', to='site_audit.siteaudit'),
        ),
        migrations.AddField(
            model_name='siteissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True),
        ),
        migrations.AddField(
            model_name='siteissue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('persisting', 'Persisting'), ('resolved', 'Resolved')], db_index=True, default='new', help_text='Track if issue is new, persisting, or resolved', max_length=20),
        ),
    ]
