# Generated by Django 5.2.5 on 2025-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0008_add_issue_lifecycle_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='pagespeed_desktop_response_r2_path',
            field=models.CharField(blank=True, help_text='R2 storage path for the raw desktop PageSpeed Insights API response', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='siteaudit',
            name='pagespeed_mobile_response_r2_path',
            field=models.CharField(blank=True, help_text='R2 storage path for the raw mobile PageSpeed Insights API response', max_length=500, null=True),
        ),
    ]
