# Generated by Django 5.2.5 on 2025-08-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0009_siteaudit_pagespeed_desktop_response_r2_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteaudit',
            name='desktop_performance',
        ),
        migrations.RemoveField(
            model_name='siteaudit',
            name='mobile_performance',
        ),
    ]
