# Generated by Django 5.2.5 on 2025-09-04 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0010_remove_performance_json_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('crawl_overview', 'Crawl Overview'), ('issues_overview', 'Issues Overview'), ('internal_all', 'Internal All'), ('external_all', 'External All'), ('response_codes', 'Response Codes'), ('page_titles', 'Page Titles'), ('meta_descriptions', 'Meta Descriptions'), ('h1', 'H1 Tags'), ('h2', 'H2 Tags'), ('images', 'Images'), ('canonicals', 'Canonicals'), ('directives', 'Directives'), ('hreflang', 'Hreflang'), ('structured_data', 'Structured Data'), ('links', 'Links'), ('javascript', 'JavaScript'), ('validation', 'Validation'), ('other', 'Other')], db_index=True, max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('r2_path', models.CharField(help_text='Path to file in R2 storage', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='text/csv', max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='MD5 or SHA256 checksum of the file', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_files', to='site_audit.siteaudit')),
            ],
            options={
                'db_table': 'audit_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['site_audit', 'file_type'], name='audit_files_site_au_543cf8_idx'), models.Index(fields=['uploaded_at'], name='audit_files_uploade_4c4356_idx')],
            },
        ),
    ]
