# Generated by Django 5.2.5 on 2025-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0011_add_audit_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfile',
            name='file_type',
            field=models.CharField(choices=[('crawl_overview', 'Crawl Overview'), ('issues_overview', 'Issues Overview'), ('internal_all', 'Internal All'), ('external_all', 'External All'), ('response_codes', 'Response Codes'), ('page_titles', 'Page Titles'), ('meta_descriptions', 'Meta Descriptions'), ('h1', 'H1 Tags'), ('h2', 'H2 Tags'), ('images', 'Images'), ('canonicals', 'Canonicals'), ('directives', 'Directives'), ('hreflang', 'Hreflang'), ('structured_data', 'Structured Data'), ('links', 'Links'), ('javascript', 'JavaScript'), ('validation', 'Validation'), ('technical_seo_audit', 'Technical SEO Audit'), ('content_optimization', 'Content Optimization'), ('technical_config', 'Technical Configuration'), ('media_analysis', 'Media Analysis'), ('link_analysis', 'Link Analysis'), ('page_performance', 'Page Performance'), ('security', 'Security & HTTPS'), ('audit_summary', 'Audit Summary'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
