# Generated by Django 5.2.5 on 2025-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_migrate_editor_to_member'),
        ('site_audit', '0012_add_excel_file_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='siteaudit',
            name='site_audits_next_sc_012de4_idx',
        ),
        migrations.RemoveIndex(
            model_name='siteaudit',
            name='site_audits_is_audi_3d8674_idx',
        ),
        migrations.AlterField(
            model_name='siteaudit',
            name='audit_frequency_days',
            field=models.IntegerField(default=30, help_text='DEPRECATED - Automatic audits no longer run on schedule'),
        ),
        migrations.AlterField(
            model_name='siteaudit',
            name='is_audit_enabled',
            field=models.BooleanField(default=False, help_text='DEPRECATED - Automatic scheduled audits are disabled'),
        ),
        migrations.AddIndex(
            model_name='siteaudit',
            index=models.Index(fields=['project', 'status'], name='site_audits_project_e4746f_idx'),
        ),
        migrations.AddIndex(
            model_name='siteaudit',
            index=models.Index(fields=['last_audit_date'], name='site_audits_last_au_d66688_idx'),
        ),
    ]
