# Generated by Django 5.2.5 on 2025-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon fetched automatically from domain', null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='project',
            name='favicon_fetched',
            field=models.BooleanField(default=False, help_text='Whether favicon fetch has been attempted'),
        ),
    ]
