# Generated by Django 5.2.5 on 2025-08-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_favicon_project_favicon_fetched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='favicon_fetched',
        ),
    ]
