# Generated by Django 5.2.5 on 2025-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_migrate_editor_to_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataforseo_keywords_path',
            field=models.CharField(blank=True, help_text='R2 path to stored DataForSEO keywords data', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataforseo_keywords_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time DataForSEO keywords were fetched', null=True),
        ),
    ]
