# Generated by Django 5.2.5 on 2025-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_add_dataforseo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataforseo_task_created_at',
            field=models.DateTimeField(blank=True, help_text='When the latest DataForSEO task was created', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataforseo_task_id',
            field=models.CharField(blank=True, help_text='Latest DataForSEO task ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataforseo_task_status',
            field=models.CharField(blank=True, help_text='Status of the latest DataForSEO task', max_length=50, null=True),
        ),
    ]
