# Generated by Django 5.2.5 on 2025-09-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_add_dataforseo_task_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dataforseo_task_created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dataforseo_task_status',
        ),
    ]
