# Generated by Django 5.2.5 on 2025-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_unused_dataforseo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backlinks_no_data_until',
            field=models.DateTimeField(blank=True, help_text='Date until which backlinks fetching is blocked due to no data', null=True),
        ),
    ]
