# Generated by Django 5.2.5 on 2025-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Unique configuration key (e.g., 'site_name', 'maintenance_mode')", max_length=255, unique=True)),
                ('value', models.TextField(help_text='Configuration value stored as text')),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('json', 'JSON'), ('text', 'Long Text')], default='str', help_text='Data type of the value for proper casting', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this configuration does')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark if this contains sensitive data (will be hidden in logs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'ordering': ['key'],
            },
        ),
    ]
