# Generated by Django 5.2.5 on 2025-08-25 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_remove_favicon_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, default='US', max_length=50)),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('on_map', models.BooleanField(default=False)),
                ('rank_status', models.CharField(choices=[('no_change', 'No Change'), ('up', 'Up'), ('down', 'Down'), ('new', 'New')], default='no_change', max_length=20)),
                ('rank_diff_from_last_time', models.IntegerField(default=0)),
                ('rank_url', models.URLField(blank=True, max_length=500, null=True)),
                ('number_of_results', models.BigIntegerField(default=0)),
                ('initial_rank', models.IntegerField(default=0)),
                ('highest_rank', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scrape_do_files', models.JSONField(blank=True, default=list)),
                ('scrape_do_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('success_api_hit_count', models.IntegerField(default=0)),
                ('failed_api_hit_count', models.IntegerField(default=0)),
                ('impact', models.CharField(choices=[('no', 'No'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='no', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('processing', models.BooleanField(db_index=True, default=False)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('is_organic', models.BooleanField(default=True)),
                ('has_map_result', models.BooleanField(default=False)),
                ('has_video_result', models.BooleanField(default=False)),
                ('has_image_result', models.BooleanField(default=False)),
                ('search_results_file', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_results', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', 'keyword'], name='keywords_ke_project_0e6062_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', 'rank'], name='keywords_ke_project_e1a208_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', 'archive'], name='keywords_ke_project_4653d7_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', '-created_at'], name='keywords_ke_project_e53f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['processing', 'archive'], name='keywords_ke_process_5d1a9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('keyword', 'country', 'project')},
        ),
        migrations.AddIndex(
            model_name='rank',
            index=models.Index(fields=['keyword', '-created_at'], name='keywords_ra_keyword_c27a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='rank',
            index=models.Index(fields=['keyword', 'rank'], name='keywords_ra_keyword_1a81f7_idx'),
        ),
        migrations.AddIndex(
            model_name='rank',
            index=models.Index(fields=['keyword', 'is_organic'], name='keywords_ra_keyword_9d4786_idx'),
        ),
    ]
