# Generated by Django 5.2.5 on 2025-09-04 04:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('project', '0004_migrate_editor_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name or title', max_length=255)),
                ('start_date', models.DateField(help_text='Report start date')),
                ('end_date', models.DateField(help_text='Report end date')),
                ('report_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('both', 'Both CSV and PDF')], default='both', max_length=10)),
                ('include_tags', models.JSONField(blank=True, default=list, help_text='Include keywords with these tags')),
                ('exclude_tags', models.JSONField(blank=True, default=list, help_text='Exclude keywords with these tags')),
                ('fill_missing_ranks', models.BooleanField(default=True, help_text="Use previous day's rank when data is missing")),
                ('include_competitors', models.BooleanField(default=False, help_text='Include competitor tracking data if available')),
                ('include_graphs', models.BooleanField(default=True, help_text='Include graphs in PDF report')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('csv_file_path', models.CharField(blank=True, help_text='R2 path to CSV file', max_length=500, null=True)),
                ('pdf_file_path', models.CharField(blank=True, help_text='R2 path to PDF file', max_length=500, null=True)),
                ('csv_file_size', models.BigIntegerField(default=0, help_text='CSV file size in bytes')),
                ('pdf_file_size', models.BigIntegerField(default=0, help_text='PDF file size in bytes')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_seconds', models.IntegerField(default=0)),
                ('send_email_notification', models.BooleanField(default=True, help_text='Send email when report is ready')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, help_text='Specific keywords to include. Leave empty for all project keywords', to='keywords.keyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_reports', to='project.project')),
            ],
            options={
                'db_table': 'keyword_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Schedule name', max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly reports', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='For monthly reports (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('time_of_day', models.TimeField(default='09:00', help_text='Time to generate report (UTC)')),
                ('report_period_days', models.IntegerField(default=7, help_text='Number of days to include in each report', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('report_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('both', 'Both CSV and PDF')], default='both', max_length=10)),
                ('include_tags', models.JSONField(blank=True, default=list)),
                ('exclude_tags', models.JSONField(blank=True, default=list)),
                ('fill_missing_ranks', models.BooleanField(default=True)),
                ('include_competitors', models.BooleanField(default=False)),
                ('include_graphs', models.BooleanField(default=True)),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses to send reports to')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, help_text='Specific keywords to include. Leave empty for all project keywords', to='keywords.keyword')),
                ('last_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='keywords.keywordreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='project.project')),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keywordreport',
            index=models.Index(fields=['project', '-created_at'], name='keyword_rep_project_3d8aac_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordreport',
            index=models.Index(fields=['status', 'created_at'], name='keyword_rep_status_ceee3b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordreport',
            index=models.Index(fields=['created_by', '-created_at'], name='keyword_rep_created_8199ec_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['project', 'is_active'], name='report_sche_project_e87def_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='report_sche_is_acti_1056cd_idx'),
        ),
    ]
