# Generated by Django 5.2.5 on 2025-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='ranking_pages',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 ranking pages with URL and position'),
        ),
    ]
