# Generated by Django 5.2.5 on 2025-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='location',
            field=models.CharField(blank=True, help_text='Location for local search (e.g., "New York, NY, United States")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_file',
            field=models.CharField(blank=True, help_text='R2 storage path for detailed rank data', max_length=500, null=True),
        ),
    ]
