# Generated by Django 5.2.5 on 2025-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_add_keyword_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordreport',
            name='report_type',
            field=models.CharField(choices=[('keyword_rankings', 'Keyword Rankings'), ('page_rankings', 'Page Rankings'), ('top_competitors', 'Top Competitors'), ('competitors_targets', 'Competitors Targets')], default='keyword_rankings', help_text='Type of report to generate', max_length=30),
        ),
        migrations.AlterField(
            model_name='keywordreport',
            name='end_date',
            field=models.DateField(blank=True, help_text='Report end date', null=True),
        ),
        migrations.AlterField(
            model_name='keywordreport',
            name='start_date',
            field=models.DateField(blank=True, help_text='Report start date', null=True),
        ),
    ]
