# Generated by Django 5.2.5 on 2025-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_location_rank_rank_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='country_code',
            field=models.CharField(db_index=True, default='US', max_length=10),
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_error_message',
            field=models.CharField(blank=True, help_text='Minimal error message', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='scrape_do_file_path',
            field=models.CharField(blank=True, help_text='Latest HTML file path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='uule',
            field=models.CharField(blank=True, help_text='UULE parameter for exact location targeting', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='scrape_do_files',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of HTML files, latest first'),
        ),
    ]
