# Generated by Django 5.2.5 on 2025-08-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_keyword_country_code_keyword_last_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='initial_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
