# Generated by Django 5.2.5 on 2025-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_add_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='top_competitors',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 competitor domains with their rankings'),
        ),
    ]
