# Generated by Django 5.2.5 on 2025-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_add_top_competitors_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='daily_queue_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for daily queue tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='expected_crawl_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this keyword is expected to be crawled', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_queue_date',
            field=models.DateField(blank=True, db_index=True, help_text='Last date keyword was queued for daily processing', null=True),
        ),
    ]
