# Generated by Django 5.2.5 on 2025-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0007_add_user_to_tags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tag',
            new_name='keywords_ta_user_id_b525bb_idx',
            old_name='keywords_ta_user_id_is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='keywords_ta_user_id_9de83e_idx',
            old_name='keywords_ta_user_id_slug_idx',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
    ]
